-- ထောပြီ platform v2 — seed data (development only). Idempotent.

USE HtawPyi;
GO

-- Admin account: INSERT is intentionally commented out because the
-- PasswordHash must be generated by the API's hasher (ASP.NET Identity
-- PasswordHasher). Once the API exists, create the admin via its
-- registration path or paste a real hash below.
--
-- IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'admin@htawpyi.local')
-- INSERT INTO dbo.Users (Email, PasswordHash, Role)
-- VALUES (N'admin@htawpyi.local', N'<paste-hash-generated-by-api>', N'Admin');

-- Sample tickets for the next draw (16 Sep 2026) so the shop has data to
-- render in development. Requires an existing user to satisfy UploadedBy —
-- runs only when the admin user above exists.
IF EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'admin@htawpyi.local')
BEGIN
    DECLARE @admin UNIQUEIDENTIFIER =
        (SELECT Id FROM dbo.Users WHERE Email = N'admin@htawpyi.local');

    INSERT INTO dbo.Tickets (DrawDate, Number, Price, UploadedBy)
    SELECT v.DrawDate, v.Number, v.Price, @admin
    FROM (VALUES
        ('2026-09-16', '417212', 120.00),
        ('2026-09-16', '250169', 120.00),
        ('2026-09-16', '888888',  300.00),
        ('2026-09-16', '135790', 120.00),
        ('2026-09-16', '024680', 120.00)
    ) AS v (DrawDate, Number, Price)
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.Tickets t
        WHERE t.DrawDate = v.DrawDate AND t.Number = v.Number
    );
END
GO
